services:
  web:
    build: .
    env_file:
      - .env  # Para cargar variables de entorno desde el archivo .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Monta todo el directorio del proyecto en /app
      - ./data:/data  # Monta volumen para persistencia de datos 
    environment:
      - FLASK_ENV=development
      - FLASK_APP=todolist.py
    command: flask run --host=0.0.0.0 --port=8000

volumes:
  data: